name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkoutcode
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
        
    - name: docker login
      env:
        Docker_user: ${{ secrets.DOCKER }}
        Docker_password: ${{ secrets.PASSWORD_DOCKER }}
      run: |
        echo "Iniciando login"
        docker login -u $Docker_user -p $Docker_password
        echo "fin del login"
        
    - name: Build Docker Image
      run: |
        docker build -t tebangiraldo/dockergraphql:1.0.0 .
        
    - name: Push Docker Image
      run: |
        docker push tebangiraldo/dockergraphql:1.0.0 
        
      
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
